import pyautogui
import time 

pyautogui.hotkey("win", "d")
pyautogui.press('win')
pyautogui.write('chrome')
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey('win', 'up')
pyautogui.write('http://www.paint.com')
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('alt')
pyautogui.press('space')
time.sleep(1)
pyautogui.press('x')
time.sleep(1)
pyautogui.dragTo(420,316, duration = 1)
pyautogui.dragTo(420, 448, duration = 1)
pyautogui.dragTo(755,448, duration = 1)
pyautogui.dragTo(755, 186, duration = 1)
pyautogui.dragTo(499, 186, duration = 1)
pyautogui.dragTo(574, 316, duration = 1)
pyautogui.dragTo(574, 443, duration = 1)
time.sleep(1)
pyautogui.dragTo(499, 186, duration = 1)
pyautogui.dragTo(420,316, duration = 1)
pyautogui.dragTo(574, 316, duration = 1)
pyautogui.dragTo(755, 316, duration = 1)
time.sleep(1)
xybalde = pyautogui.locateCenterOnScreen('desenhar\\balde.png', confidence=0.95)
pyautogui.click(xybalde)
time.sleep(1)
xymarron = pyautogui.locateCenterOnScreen('desenhar\\marron.png', confidence=0.95)
pyautogui.click(xymarron)
time.sleep(1)
pyautogui.dragTo(491, 183, duration = 1)
pyautogui.dragTo(392,322, duration = 1)
time.sleep(1)
pyautogui.press('ctrl')
pyautogui.press('s')
time.sleep(2)